### ISSUE TITLE
 please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [rhinstaller/system-config-kickstart#8]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:

* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:

* For github and gitlab hosted projects, Weblate open pull request. For other git hosting, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by Jibec** [comment]
Kind reminder, Zanata will be removed in a few weeks now: https://bugzilla.redhat.com/show_bug.cgi?id=1854445

**Comment by VladimirSlavik** [comment]
I think we'll mothball this project rather than keep going...

**Comment by jkonecny12** [comment]
Hello @Jibec, I've created https://github.com/rhinstaller/system-config-kickstart/pull/9 to archive this project. There is no active development and it's even not packaged to newer Fedora. We won't migrate the translations to Weblate for this project.

However, our current team members are not part of the team anymore. I can reach them but if you are able to close the Zanata project it would be great. Thanks!
